language: python
python:
  - "2.7"
  - "3.3"
# command to install dependencies
install:
  - "pip install -r requirements/external_apps.txt"
  - "pip install -r requirements/test_apps.txt"
  - "pip install coveralls"
# command to run tests
script: "coverage run --source=pages python pages/test_runner.py"
after_success:
  coveralls
