sudo: false

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "nightly"

env:
  - >
    REQUIREMENTS=min
    DJANGO="Django==1.8.0"
  - >
    REQUIREMENTS=pypi
    DJANGO="Django<1.10"
  - >
    REQUIREMENTS=dev
    DJANGO="Django<1.10"

before_install:
  - "pip install coveralls git+https://github.com/greut/requirements-builder@output#egg=requirements-builder"
  - "requirements-builder --level=min setup.py > requirements-min.txt"
  - "requirements-builder --level=pypi setup.py > requirements-pypi.txt"
  - "requirements-builder --level=dev --req=requirements-devel.txt setup.py > requirements-dev.txt"

install:
  - "pip install -r requirements-${REQUIREMENTS}.txt"
  - "pip install ${DJANGO}"
  - "pip install -e .[tests]"

script:
  - "coverage run --source=pages pages/test_runner.py"

after_success:
  - "coveralls"
