version: '3'
# skip the build process by using the image

services:
  db:
    image: postgres
  web:
    image: docker.pkg.github.com/batiste/django-page-cms/cms:latest
    command: bash -c "python example/manage.py migrate && python example/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    depends_on:
      - db
  